In [ ]:
# Goal: Understand the difference between covariance and correlation.
# Data: x = [1, 2, 3, 4], y = [2, 4, 6, 8]
# Tasks
# (a) Determine whether x and y tend to move in the same direction or opposite directions. Explain why.
# (b) Create a Pandas DataFrame using x and y. Calculate the covariance between the two variables using Pandas.
# (c) Calculate the Pearson correlation coefficient between x and y using Pandas.
# (d) Explain why covariance depends on the measurement units of the variables, while correlation is standardised and ranges from -1 to +1.

In [1]:
import pandas as pd

In [9]:
x = [1, 2, 3, 4]
y = [2, 4, 6, 8]

dict = {
    "x": x,
    "y": y
}

In [11]:
df = pd.DataFrame(dict)

cova = df.cov()
cova

          x         y
x  1.666667  3.333333
y  3.333333  6.666667

In [12]:
corre = df.corr()
corre

     x    y
x  1.0  1.0
y  1.0  1.0