In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
#Count missing values in every column.

missing_values_count = df.isnull().sum()
missing_values_count

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
missing_proportion = df.isnull().mean()

print(missing_proportion)

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [14]:
df[df["Age"].isnull()].head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C

In [17]:
#Check whether complete rows are duplicated.

duplicates = df.duplicated().sum()
duplicates

np.int64(0)

In [20]:
#Inspect unique values for Survived, Pclass, Sex, and Embarked.

columns = ["Survived", "Pclass", "Sex", "Embarked"]

for col in columns:
    print(col, df[col].unique())

Survived [0 1]
Pclass [3 1 2]
Sex <StringArray>
['male', 'female']
Length: 2, dtype: str
Embarked <StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [21]:
columns = ["Age", "Fare", "SibSp", "Parch"]

for col in columns:
    print(col, "Min:", df[col].min(), "Max:", df[col].max())

Age Min: 0.42 Max: 80.0
Fare Min: 0.0 Max: 512.3292
SibSp Min: 0 Max: 8
Parch Min: 0 Max: 6

In [26]:
minmax_coloumns = ["Age","Fare","SibSp","Embarked"]

for col in minmax_coloumns:
    print(f"{col} Min: {df[col].min()} Max: {df[col].max()}")

Age Min: 0.42 Max: 80.0
Fare Min: 0.0 Max: 512.3292
SibSp Min: 0 Max: 8
Embarked Min: C Max: S

In [32]:
# Produce descriptive statistics for Age, Fare, SibSp, and Parch.

print("Age:\n", df["Age"].describe())

Age:
 count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [39]:
df[["Age","SibSp","Fare","Parch"]].describe()

              Age       SibSp        Fare       Parch
count  714.000000  891.000000  891.000000  891.000000
mean    29.699118    0.523008   32.204208    0.381594
std     14.526497    1.102743   49.693429    0.806057
min      0.420000    0.000000    0.000000    0.000000
25%     20.125000    0.000000    7.910400    0.000000
50%     28.000000    0.000000   14.454200    0.000000
75%     38.000000    1.000000   31.000000    0.000000
max     80.000000    8.000000  512.329200    6.000000

In [44]:
# Compare the mean and median for Age and Fare.
coloumn = ["Age","Fare"]

for col in coloumn:
    print(f"{col}: \nMean:{df[col].mean()}\nMedian:{df[col].median()}\n")

Age:
Mean:29.69911764705882
Median:28.0

Fare:
Mean:32.204207968574636
Median:14.4542